name: lintbot
run-name: Linting for PR
on:

  workflow_run:
    workflows: [push-build-release]
    types:
      - completed
jobs:
  download-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      pull-requests: write
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: lint
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Read pr number
        id: getprn
        run: |
          cat pr_number
          echo "prn=$(cat pr_number)" >> $GITHUB_OUTPUT

      - name: 'Run reviewer'
        uses: EddyTheCo/qmllint-action/@main
        with:
          jsondir:  ${{ github.workspace }}
          pr_number: ${{ steps.getprn.outputs.prn }}

      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: *.yaml
          pull_request_id: ${{ steps.getprn.outputs.prn }} 
